version: '3.8'
services:
  sd-node:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # MAP THE HOST FOLDER TO THE CONTAINER
      - ./models:/app/models
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G